name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
    steps:
      - name: Current date
        run: |
          date
    steps:
      - name: Directiory content
        run: |
          ls -l
